### ISSUE TITLE
Downloaded audio is distorted

### ISSUE THREAD

**Issue by mkiley** [LibraryOfCongress/citizen-dj#18]
Hello,

I  love this project! However, when I downloaded the audio, and import it into Ableton Live, the audio is heavily distorted. Usually, Ableton is really good at handling all types of audio, so I am stumped. It plays great in iTunes, but sounds broken in Ableton. I even changed the bit and sample rates of the Ableton file to match those of the audio content, and it still did not help. Any ideas?

**Comment by beefoo** [comment]
Hi! Yes, other users have [seen similar issues](https://github.com/LibraryOfCongress/citizen-dj/issues/14), and I believe the problem was related to bitrate.  I updated the sample files last night, so if you re-download them (sorry!) hopefully it should work now.  Let me know if you still see any issues!

Duplicate of #14

**Comment by mkiley** [comment]
That seems to have fixed it! Thank you so much!
